### ISSUE TITLE
Put open halls and closed halls into separate lists

### ISSUE THREAD

**Issue by WuChris** [hmoco/hungryhippo#2]
Call render_template with only the open halls and closed halls list. Check for hall status in main.py instead of time.html.

**Comment by hmoco** [comment]
I can work on a way to do so tomorrow. Do you plan on sending the two lists as the only arguments on render_template() on main.py?

**Comment by WuChris** [comment]
Yes, just send those two lists and have two loops in time.html. Sending a separate names set looks pretty dumb.

So we should do this stuff first:
1.) Change the DiningHall class to have a 'name' member variable and edit all the instantiation calls accordingly.
2.) Change 'halls' from a dictionary to a list.
